// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using masifAPI.Data;

#nullable disable

namespace masifAPI.Migrations
{
    [DbContext(typeof(IncidentContext))]
    partial class IncidentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("masifAPI.Model.Incident", b =>
                {
                    b.Property<long>("ReportID")
                        .HasColumnType("bigint")
                        .HasColumnName("ReportID");

                    b.Property<long>("IdentityUser")
                        .HasColumnType("bigint")
                        .HasColumnName("IdentityUser");

                    b.Property<long>("FoodID")
                        .HasColumnType("bigint")
                        .HasColumnName("FoodID");

                    b.Property<decimal>("ItemPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ItemPrice");

                    b.Property<decimal>("ValueIncident")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValueIncident")
                        .HasComputedColumnSql("2 * [ItemPrice]");

                    b.HasKey("ReportID", "IdentityUser");

                    b.ToTable("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
